### ISSUE TITLE
cp-kafka-connect - CONNECT_REST_PORT not read

### ISSUE THREAD

**Issue by RuiLoureiro** [confluentinc/kafka-images#146]
When using the following configuration inside a `docker-compose.yml`, the kafka-connect rest API is still on the default port (`8083`).
```yaml
kafka-connect:
  image: confluentinc/cp-kafka-connect:7.0.1
  ports:
    - 28082:28082
    - 8083:8083
  depends_on:
    - kafka
  environment:
    CONNECT_BOOTSTRAP_SERVERS: 'kafka:9093'
    CONNECT_GROUP_ID: kafka-connect
    CONNECT_REST_PORT: 28082
    CONNECT_CONFIG_STORAGE_TOPIC: _connect-configs
    CONNECT_OFFSET_STORAGE_TOPIC: _connect-offsets
    CONNECT_STATUS_STORAGE_TOPIC: _connect-status
    CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
    CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
```

From the `CONNECT_REST_PORT` environment variable, shouldn't it be reachable at `28082`?
