### ISSUE TITLE
Latest versions of kafka crash on startup

### ISSUE THREAD

**Issue by gradovenko** [confluentinc/kafka-images#147]
Hello. I am trying to run kafka version 7.0.1 / 7.0.1-3-ubi8 / 7.0.0 / 6.1.4 / 6.1.4-3-ubi8 / 6.0.5 and on either version I get the same error:

```
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
===> Running preflight checks ...
===> Check if /var/lib/kafka/data is writable ...
Command [/usr/local/bin/dub path /var/lib/kafka/data writable] FAILED !
```

On kafka versions 5.5.7 / 5.4.6 the situation is no better, but there I get a different error:

```
[main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper/192.168.32.4:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
at sun.nio.ch.IOUtil.read(IOUtil.java:192)
at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1223)
```

The latest working version for me is kafka 5.3.7. Any ideas how to solve this problem so that I can use the latest versions of kafka?

**Further technical details:**
Kafka version: 7.0.1 / 7.0.1-3-ubi8 / 7.0.0 / 6.1.4 / 6.1.4-3-ubi8 / 6.0.5 / 5.5.7 / 5.4.6
Operating system: Linux Mint 20.2

**Comment by donatelloOo** [comment]
Please see this related issue https://github.com/confluentinc/kafka-images/issues/76

In order to run on restricted cluster, multiple updates have to be done on Kubernetes manifests when using `cp-kafka:7.0.1`, including:
```
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      containers:
      - name: kafka-broker
        env:
        - name: LOG_DIR
          value: /var/tmp
        workingDir: /var/tmp
  securityContext:
    fsGroup: 1000	# default to appuser -- must be overridden on RHOCP
    runAsUser: 1000	# default to appuser -- must be overridden on RHOCP
```

**Comment by gradovenko** [comment]
> Please see this related issue #76
> 
> In order to run on restricted cluster, multiple updates have to be done on Kubernetes manifests when using `cp-kafka:7.0.1`, including:
> 
> ```
> apiVersion: apps/v1
> kind: StatefulSet
> spec:
>   template:
>     spec:
>       containers:
>       - name: kafka-broker
>         env:
>         - name: LOG_DIR
>           value: /var/tmp
>         workingDir: /var/tmp
>   securityContext:
>     fsGroup: 1000	# default to appuser -- must be overridden on RHOCP
>     runAsUser: 1000	# default to appuser -- must be overridden on RHOCP
> ```

Thanks for the answer. I understood your idea. I saw that you mentioned Kubernetes. I don't use Kubernetes in my projects, but I use docker compose. Here is my docker-compose.yaml:

```yaml
version: '3.6'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    volumes:
      - ${MYPROJECT_DATA_DIR:-/var/lib/myproject}/zookeeper/data:/var/lib/zookeeper/data
      - ${MYPROJECT_DATA_DIR:-/var/lib/myproject}/zookeeper/log:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    restart: always
    networks:
      - myproject-network
    ports:
      - ${MYPROJECT_KAFKA_PORT:-9092}:9092

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    volumes:
      - ${MYPROJECT_DATA_DIR:-/var/lib/myproject}/kafka/data:/var/lib/kafka/data
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_HEAP_OPTS=-Xmx512M
    restart: always
    depends_on:
      - zookeeper
    networks:
      - myproject-network
    ports:
      - ${MYPROJECT_ZOOKEEPER_PORT:-2181}:2181
```

Can I somehow change the "workingDir" in this case?
