### ISSUE TITLE
How to change Timezone for all kafka images

### ISSUE THREAD

**Issue by Taymindis** [confluentinc/kafka-images#148]
I have been trying a lot of way to change timezone from k8s but it is not working 
for e.g.

set ENV TZ: Asia/Singapore
mount localtime to local host path

```yaml
env:
 - name: TZ
    value: "{{ .Values.timezone }}"


volumeMounts:
- name: tz-config
  mountPath: /etc/localtime
- name: tz-name
  mountPath: /etc/timezone


volumes:
- name: tz-config
  hostPath:
    path: /usr/share/zoneinfo/Asia/Singapore
    type: File
- name: tz-name
  hostPath:
    path: /etc/timezone
    type: File
```
