### ISSUE TITLE
why this is not working? `services.kafka.environment.KAFKA_AUTO_CREATE_TOPICS_ENABLE contains true, which is an invalid type, it should be a string, number, or a null`

### ISSUE THREAD

**Issue by seunggabi** [confluentinc/kafka-images#170]
```
services.kafka.environment.KAFKA_AUTO_CREATE_TOPICS_ENABLE contains true, which is an invalid type, it should be a string, number, or a null
```

```
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
vs
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
```

### not working
```yaml
kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka
    container_name: data-instant_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      data_api_net:
        ipv4_address: 172.16.240.18
```

### it's works
```yaml
kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka
    container_name: data-instant_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      data_api_net:
        ipv4_address: 172.16.240.18
```
