### ISSUE TITLE
cp-kafka-connect - not able to load SMT file from /usr/share/java

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/kafka-images#171]
Even though the **plugin InsertUuid-1.0-SNAPSHOT.jar is loaded successfully** as indicated in the below docker compose file
```
[2022-07-02 16:38:17,773] INFO Loading plugin from: /usr/share/java/InsertUuid-1.0-SNAPSHOT.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
[2022-07-02 16:38:17,804] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/InsertUuid-1.0-SNAPSHOT.jar/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
```

I get the below error when I try to POST a connector containing the SMT
```
{
  "error_code": 400,
  "message": "Connector configuration is invalid and contains the following 2 error(s):\nInvalid value com.github.cjmatta.kafka.connect.smt.InsertUuid$Value for configuration transforms.insertID.type: Class com.github.cjmatta.kafka.connect.smt.InsertUuid$Value could not be found.\nInvalid value null for configuration transforms.insertID.type: Not a Transformation\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"
}
```
I am using **cp-kafka-connect:latest** docker image and my connector config is as follows

```
{
    "name": "cosmosdb-sink-connector",
    "config": {
        "connector.class": "com.azure.cosmos.kafka.connect.sink.CosmosDBSinkConnector",
        "tasks.max": 3,
        "topics": "mynamespace-myapp-mytopic-sandbox-private",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "key.converter.schemas.enable": "false",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
        "connect.cosmos.connection.endpoint": "https://[redacted].documents.azure.com:443/",
        "connect.cosmos.master.key": "[redacted]",
        "connect.cosmos.databasename": "kafka-db",
        "connect.cosmos.containers.topicmap": "mynamespace-myapp-mytopic-sandbox-private#verification",
        "transforms": "insertID",
        "transforms.insertID.type": "com.github.cjmatta.kafka.connect.smt.InsertUuid$Value",
        "transforms.insertID.uuid.field.name": "id"
    }
}
```

The mapping in the docker-compose file is as below
```
connect:
    image: ${REPOSITORY}/cp-kafka-connect:${CONNECT_DOCKER_TAG}
    hostname: kafka-connect
    container_name: kafka-connect
    ports:
      - "8083:8083"
    volumes:
      - "/usr/share/confluent-hub-components/:/usr/share/confluent-hub-components/"
      - "/usr/local/kafka-connect-insert-uuid/target/InsertUuid-1.0-SNAPSHOT.jar:/usr/share/java/InsertUuid-1.0-SNAPSHOT.jar"
    environment:
           .......
```

Any idea on why the error?

Thanks.
