### ISSUE TITLE
Set memory limits for confluentinc/confluent-local image

### ISSUE THREAD

**Issue by hyzyla** [confluentinc/kafka-images#252]
I would like to reduce memory consumtion by kafka for local development 

I've tried setting like that:
```yaml
  kafka:
    image: confluentinc/confluent-local
    ports: ["9092:9092"]
    environment:
      KAFKA_OPTS: "-Xmx256m -Xms256m"
```

but got error:
```
 ===> Check if kafka brokers are up
kafka-1  | Invalid maximum heap size: -Xmx256m -Xms256m
kafka-1  | Error: Could not create the Java Virtual Machine.
kafka-1  | Error: A fatal exception has occurred. Program will exit.
kafka-1  | Error: kafka-ready check failed
kafka-1  | Usage:
kafka-1  |   ub kafka-ready <min-num-brokers> <timeout-secs> [flags]
kafka-1  | 
kafka-1  | Flags:
kafka-1  |   -b, --bootstrap-servers string   comma-separated list of kafka brokers
kafka-1  |   -c, --config string              path to the config file
kafka-1  |   -h, --help                       help for kafka-ready
kafka-1  |   -s, --security string            security protocol to use when multiple listeners are enabled.
kafka-1  |   -z, --zookeeper-connect string   zookeeper connect string
kafka-1  | 
kafka-1  | ===> Launching kafka-rest ... 
```

How to set memory limits for JVM for confluentinc/confluent-local image
