### ISSUE TITLE
Bash is being deleted on zookeeper container start

### ISSUE THREAD

**Issue by mastery-benjamin-palko** [confluentinc/kafka-images#291]
Hello, I'm having an issue where both my `/bin/bash` & `/sbin/ldconfig` are being deleted when starting the latest zookeeper image through docker-compose.

### System Specs
OS: Ubuntu 22.04.4 LTS x86_64 
Host: 21K5001BUS ThinkPad P14s Gen 4 
Kernel: 6.5.0-1020-oem 
CPU: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics (16) @ 5.132GHz 
GPU: AMD ATI 64:00.0 Device 15bf 

### Docker info
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

### Config
```yaml
...

zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper-offers
    container_name: zookeeper-offers
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
...
```

Downgrading from `latest` to `7.2.9` has temporarily fixed the issue but this is not a suitable long term fix.
