### ISSUE TITLE
 Heartbeat poll expired, leaving group. Leaving consumer group

### ISSUE THREAD

**Issue by haseebkhawaja** [confluentinc/kafka-images#343]
I am using this docker-compose 

```
version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Kafka broker port
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Replace 'your.local.IP.address' with your actual local network IP
      KAFKA_ADVERTISED_LISTENERS: plaintext://10.100.103.201:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
```
**I am facing this issue most of the time**
**2024-07-30 11:06:58,309 - WARNING - Heartbeat poll expired, leaving group
2024-07-30 11:06:58,310 - INFO - Leaving consumer group (os_ai_req_grp_3)**
 
 **To overcome this issue** 
I changes the consumer group name after facing the above mentioned issue.. like change from "os_ai_req_grp_3" to "os_ai_req_grp_4"
 **But the problem is that** 
 I don't know when the consumer group has been left... It may be after some mints, may be after hours or may be after 1 day.... but it leaves....
 
 So, I am interested in the solution as I cannot change the name of consumer group each time... I want automated solution....
 <<< **Suggest me reliable solution** >>> 
 
 Thanks in advance
