### ISSUE TITLE
Env KAFKA_PARTITION_ASSIGNMENT_STRATEGY ignored by Kafka

### ISSUE THREAD

**Issue by indywidualny** [confluentinc/kafka-images#45]
We're trying to change partition assignment strategy. We manage Kafka cluster with Docker Compose like this:

```
  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    networks:
      - test
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      # some more env here...
      KAFKA_PARTITION_ASSIGNMENT_STRATEGY: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    deploy:
      placement:
        constraints:
          - node.role == manager
```

First we tried to use Kafka image `confluentinc/cp-kafka:5.3.1` but apparently it has Kafka version inside which doesn't support Partition Assignment Strategy we're interested in (`org.apache.kafka.clients.consumer.CooperativeStickyAssignor`). - BTW, what's wrong with version naming here... They don't make any sense.

Anyway, we switched to `confluentinc/cp-kafka:5.5.1` and applied the partition assignment strategy like in the snippet above. Still no luck, we see in Kafka logs this ENV was recognized but the config wasn't modified with the chosen strategy. During Kafka startup a full config is printed so we noticed our custom value is not there.

Is something wrong with the image? How to really apply `org.apache.kafka.clients.consumer.CooperativeStickyAssignor` partition assignment strategy? 

If it's not a bug and changing the strategy is possible, a quick instruction how to do it would help us very much. Like which image to use, how to apply the strategy, how to verify it's working. Looking forward to hearing from you.
