### ISSUE TITLE
Kafka Connect HEALTHCHECK startup catch-22

### ISSUE THREAD

**Issue by infogulch** [confluentinc/kafka-images#50]
In Dockerfile.ubi8 the cp-kafka-connect image is configured with a `HEALTHCHECK` command that is used by docker to determine the health of the Kafka Connect container:

https://github.com/confluentinc/kafka-images/blob/6369da3b5fe18159571ccb2796ca8ed076935b8d/kafka-connect-base/Dockerfile.ubi8#L81-L82

The `healthcheck.sh` script uses the container configured `CONNECT_REST_ADVERTISED_HOST_NAME` to try to connect to the named host as an indication that the container is healthy. This variable should be some hostname that can be resolved.

https://github.com/confluentinc/kafka-images/blob/6369da3b5fe18159571ccb2796ca8ed076935b8d/kafka-connect-base/include/etc/confluent/docker/healthcheck.sh#L4

However, when one tries to set the hostname to the internal connect container name in a docker deployment, we run into a catch-22:  Docker will wait for healthcheck.sh to report healthy before adding the container name to docker's internal network DNS, but connect will never be able to resolve that DNS name because the container is not yet marked as healthy. Thus it will stay in the "starting" state indefinitely, or until it's shutdown/restarted by the docker daemon.

For example, the following docker compose config will never report a healthy container, even though the name "kafka-connect-01" would be perfectly valid, resolvable name for kafka-connect-02 to use after it completes startup, etc.

```
  kafka-connect-01:
    image: confluentinc/cp-kafka-connect:5.5.1
    container_name: kafka-connect-01
    ports:
      - 18083:8083
    environment:
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect-01"
      ...

  kafka-connect-02:
    image: confluentinc/cp-kafka-connect:5.5.1
    container_name: kafka-connect-02
    ports:
      - 18083:8083
    environment:
      CONNECT_REST_PORT: 8083
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect-02"
      ...
```

To resolve this, I think `healthcheck.sh` should **not** use the `$CONNECT_REST_ADVERTISED_HOST_NAME` variable, and use `localhost` instead, which will try to connect to the locally running (to the container) instance of connect.  This will have the following benefits:

* This will allow Worker communication to happen over the internal docker network (the motivation for this issue)
* It will prevent incorrectly reporting a healthy container status in the case where `CONNECT_REST_ADVERTISED_HOST_NAME` is misconfigured to point to some other Worker
* It represents a better separation of responsibilities because the status of the healthcheck of the container does not depend on being able to resolve the container's own hostname
