### ISSUE TITLE
Container cp-zookeeper doesn't allow the use of custom node IDs

### ISSUE THREAD

**Issue by samcarpentier** [confluentinc/kafka-images#65]
### Introduction

I believe that I have found a bug related to the templates used to generate the Zookeeper configuration files, when it comes to clustering.

As stated in the [Zookeeper's Admin documentation](https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_clusterOptions), under the `server.x=[hostname]:nnnnn[:nnnnn]` configuration key:

> When the server starts up, it determines which server it is by looking for the **file myid** in the data directory. That **file contains the server number**, in ASCII, and **it should match x in server.x** in the left hand side of this setting.

Unfortunately, there is a major discrepancy that can be found in the Zookeeper templated config files of this project, which prevents users from using custom IDs for their Zookeeper nodes:

1. In file `zookeeper/include/etc/confluent/docker/configure` at line 31 ([link](https://github.com/confluentinc/kafka-images/blob/v5.5.0/zookeeper/include/etc/confluent/docker/configure#L31)), we can see that the content of the environment variable `ZOOKEEPER_SERVER_ID` will be written to the `myid` file of the Zookeeper node. This ID can be any value between 1 and 255 and can be freely defined by the user. **This is the expected behaviour.**

2. In file `zookeeper/include/etc/confluent/docker/zookeeper.properties.template` at line 84 ([link](https://github.com/confluentinc/kafka-images/blob/v5.5.0/zookeeper/include/etc/confluent/docker/zookeeper.properties.template#L84)), the section of the script that generates the `server.x=` configurations will automatically assign the `loop.index` as the server ID/number to each server listed in the environment variable `ZOOKEEPER_SERVERS`. **This is WRONG**.

### Working example

In *most* cases, the current setup will work just fine, because users will tend to use node IDs that start at index 1.

| Zookeeper node | `ZOOKEEPEER_SERVER_ID` | `ZOOKEEPER_SERVERS` |
| :--- | :--- | :--- |
| `zk1.example.com` (10.0.0.1) | 1 | `10.0.0.1:2888:3888,10.0.0.2:2888:3888,10.0.0.3:2888:3888` |
| `zk2.example.com` (10.0.0.2) | 2 | `10.0.0.1:2888:3888,10.0.0.2:2888:3888,10.0.0.3:2888:3888` |
| `zk3.example.com` (10.0.0.3) | 3 | `10.0.0.1:2888:3888,10.0.0.2:2888:3888,10.0.0.3:2888:3888` |

The generated configuration file will contain the following values:

```properties
# /etc/kafka/zookeeper.properties
server.1=10.0.0.1:2888:3888
server.2=10.0.0.2:2888:3888
server.3=10.0.0.3:2888:3888
```

**Result: Zookeeper starts and runs just fine ✅** 

### Non-functional example

Now, let's reuse the same situation than above with only a slight variation: let's start node IDs at index 100.

| Zookeeper node | `ZOOKEEPEER_SERVER_ID` | `ZOOKEEPER_SERVERS` |
| :--- | :--- | :--- |
| `zk1.example.com` (10.0.0.1) | 101 | `10.0.0.1:2888:3888,10.0.0.2:2888:3888,10.0.0.3:2888:3888` |
| `zk2.example.com` (10.0.0.2) | 102 | `10.0.0.1:2888:3888,10.0.0.2:2888:3888,10.0.0.3:2888:3888` |
| `zk3.example.com` (10.0.0.3) | 103 | `10.0.0.1:2888:3888,10.0.0.2:2888:3888,10.0.0.3:2888:3888` |

Because of the `server.{{ loop.index }}={{ server }}` statement, the generated configuration file will contain the following values (note that the node IDs don't match!!!):

```properties
# /etc/kafka/zookeeper.properties
server.1=10.0.0.1:2888:3888
server.2=10.0.0.2:2888:3888
server.3=10.0.0.3:2888:3888
```

**Result: Zookeeper will NOT start properly and will never be able to establish quorum with the other nodes in the cluster ❌**

Since `cp-zookeeper` is allowing users to define a custom node ID value via `ZOOKEEPER_SERVER_ID`, the generated `zookeeper.properties` file should be generated with these custom IDs:

```properties
# /etc/kafka/zookeeper.properties
server.101=10.0.0.1:2888:3888
server.102=10.0.0.2:2888:3888
server.103=10.0.0.3:2888:3888
```

### Conclusion

In summary, the core of the problem resides in `/zookeeper/include/etc/confluent/docker/zookeeper.properties.template` at line 84 ([link](https://github.com/confluentinc/kafka-images/blob/v5.5.0/zookeeper/include/etc/confluent/docker/zookeeper.properties.template#L84)). The `loop.index` variable should NOT be used to generate this file. 

There should be a mechanism built-in the syntax of `ZOOKEEPER_SERVERS` to define the node IDs of each member of the cluster. For instance:

```
ZOOKEEPER_SERVERS="10.0.0.1:2888:3888:101,10.0.0.2:2888:3888:102,10.0.0.3:2888:3888:103"
```

Or, a dedicated environment variable could be use to override this default ID mapping:

```
ZOOKEEPER_SERVERS_ID_MAPPING="10.0.0.1:101,10.0.0.2:102,10.0.0.1:103"
```

Let me know what you think about this and you encountered the same issue in the past with other users.
Thanks!

**Comment by samcarpentier** [comment]
Please find attached [docker-compose.yml.zip](https://github.com/confluentinc/kafka-images/files/5816367/docker-compose.yml.zip) file that can help reproduce the issue.

Logs:

```
zookeeper-1  | ===> Printing /var/lib/zookeeper/data/myid
zookeeper-1  | 101===> Launching zookeeper ...
zookeeper-1  | ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain)
zookeeper-1  | java.lang.RuntimeException: My id 101 not in the peer list
zookeeper-1  | 	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:885)
zookeeper-1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
zookeeper-1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
zookeeper-1  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)

zookeeper-2  | ===> Printing /var/lib/zookeeper/data/myid
zookeeper-2  | 102===> Launching zookeeper ...
zookeeper-2  | ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain)
zookeeper-2  | java.lang.RuntimeException: My id 102 not in the peer list
zookeeper-2  | 	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:885)
zookeeper-2  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
zookeeper-2  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
zookeeper-2  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)

zookeeper-3  | ===> Printing /var/lib/zookeeper/data/myid
zookeeper-3  | 103===> Launching zookeeper ...
zookeeper-3  | ERROR Unexpected exception, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain)
zookeeper-3  | java.lang.RuntimeException: My id 103 not in the peer list
zookeeper-3  | 	at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:885)
zookeeper-3  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:205)
zookeeper-3  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:123)
zookeeper-3  | 	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)

zookeeper-1 exited with code 1
zookeeper-2 exited with code 1
zookeeper-3 exited with code 1
```

Thanks!

**Comment by Veryfirefly** [comment]
Hi! How to use docker swarm to deploy Kafka cluster? My zookeeper cluster node cannot access each other.
This my docker-compose-stack.yaml. The docker operation I use this: `docker stack deploy -c docker-compose-stack.yaml zookeeper` . Thank you.

``` yaml
version: '3.8'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zoo1
    container_name: zookeeper1
    networks:
      - zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: 0.0.0.0:2888:3888;zoo2:2888:3888;zoo3:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
      CONTAINER_TIMEZONE: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
  zoo2:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zoo2
    container_name: zookeeper2
    networks:
      - zookeeper
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zoo1:2888:3888;0.0.0.0:2888:3888;zoo3:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
      CONTAINER_TIMEZONE: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
  zoo3:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zoo3
    container_name: zookeeper3
    networks:
      - zookeeper
    ports:
      - "2183:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zoo1:2888:3888;zoo2:2888:3888;0.0.0.0:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
      CONTAINER_TIMEZONE: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
networks:
  zookeeper:
    driver: overlay
```
