### ISSUE TITLE
Starting container process caused: chdir to cwd (\"/home/appuser\") set in config.json failed: permission denied" 

### ISSUE THREAD

**Issue by cedric66** [confluentinc/kafka-images#76]
Image: confluentinc/cp-kafka:6.1.0

We are migrating from version 5.5.1 to 6.1.0.

During pod startup create container process fails with below error message

Error: container create failed: time="2021-03-10T07:30:19Z" level=error msg="container_linux.go:366: starting container process caused: chdir to cwd (\"/home/appuser\") set in config.json failed: permission denied" 

Can you investigate please? Thanks.

**Comment by rajan123456** [comment]
+1
Facing the same error in a secure cluster

**Comment by rajan123456** [comment]
Was able to solve and get the initContainer to work successfully. Changed the deployment to ensure it runs as user 1000.

```
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
```

**Comment by donatelloOo** [comment]
On restricted clusters like RHOCP, you cannot chose the user, it's provided by the cluster, so this WA does not work.
The issue comes from the image that is set with a workdir on appuser home:
```
$ docker inspect confluentinc/cp-kafka:7.0.1 | grep WorkingDir
            "WorkingDir": "/home/appuser",
            "WorkingDir": "/home/appuser",
```
Indeed, this folder have very limited permissions:
```
$ ls -l /home/
total 4
drwx------ 2 appuser appuser 4096 Jan 11 22:08 appuser
```
So the correct workaround is to update the workingDir before launching the container, which is on kubernetes:
```
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:
      containers:
      - workingDir: /var/lib/kafka
```
`/var/lib/kafka` is a folder with following permissions, which allow any cluster provided user being into the `root` group to have access.
```
$ ls -al /var/lib/kafka/
total 16
drwxr-x--- 3 appuser root 4096 Jan 11 22:18 .
drwxr-xr-x 1 root    root 4096 Jan 11 22:19 ..
drwxrwxr-x 2 appuser root 4096 Jan 11 22:18 data
```
That's it !

Maintainers, please update image with WORKDIR set to a folder giving `rx` access to `root` group (like `/var/lib/kafka/` or another one)
```
WORKDIR /var/lib/kafka/
```
Thanks.
