### ISSUE TITLE
Permission denied on custom configuration management

### ISSUE THREAD

**Issue by LeonardMeyer** [confluentinc/kafka-images#83]
Hi. I'm having an issue with running a custom configuration management as per indicated in the [documentation](https://docs.confluent.io/platform/current/installation/docker/development.html#change-configuration-management).  In the following I used CP 5.5.3. My Docker file looks like this : 

```
ARG CONFLUENT_DOCKER_TAG

FROM confluentinc/cp-kafka-connect-base:${CONFLUENT_DOCKER_TAG}

COPY include/etc/confluent/docker /etc/confluent/docker

RUN wget -qO- --content-disposition https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-olingo2-kafka-connector/0.9.0/camel-olingo2-kafka-connector-0.9.0-package.tar.gz | tar xvzf - -C /usr/share/java

RUN confluent-hub install --no-prompt castorm/kafka-connect-http:0.7.6 && \
    confluent-hub install --no-prompt confluentinc/kafka-connect-http:1.3.0 && \
    confluent-hub install --no-prompt jcustenborder/kafka-connect-transform-xml:0.1.0.18 && \
    confluent-hub install --no-prompt mmolimar/kafka-connect-fs:1.3.0)
```

My docker-compose connect part is this : 

```
connect:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFLUENT_DOCKER_TAG: ${CONFLUENT_DOCKER_TAG}
    image: mediation/kafka-connect:${CONFLUENT_DOCKER_TAG}
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8083:8083"
    environment:
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: "zookeeper:2181"
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
```

When I run my `docker-compose up --build`, I get this : 

```
connect            | ===> User
connect            | uid=0(root) gid=0(root) groups=0(root)
connect            | ===> Configuring ...
connect            | /etc/confluent/docker/run: line 26: /etc/confluent/docker/configure: Permission denied
```

If I run the same with CP latest version I get this : 
```
connect            | ===> User
connect            | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
connect            | ===> Configuring ...
connect            | /etc/confluent/docker/run: line 26: /etc/confluent/docker/configure: Permission denied
```

I saw in both latest and 5.5.3 kafka-connect-base Dockerfile that the COPY is done the same way : 

`COPY --chown=appuser:appuser include/etc/confluent/docker /etc/confluent/docker`

Out of curiosity I tried the same line in my Connect Dockerfile (using uid:gid) with latest version but I still have : 

```
connect            | ===> User
connect            | uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
connect            | ===> Configuring ...
connect            | /etc/confluent/docker/run: line 26: /etc/confluent/docker/configure: Permission denied
```

Which is weird because if I override the CMD directive in my Dockerfile with a `ls`, I can see : 

```
connect            | -rwxr-xr-x 1 appuser appuser 1199 Mar 17 02:50 apply-mesos-overrides
connect            | -rw-r--r-- 1 appuser appuser  775 Mar 17 02:36 bash-config
connect            | -rw-rw-r-- 1 appuser appuser 2160 Apr 19 09:02 configure
connect            | drwxrwxr-x 2 appuser appuser   53 Apr 19 10:27 connectors
connect            | -rwxr-xr-x 1 appuser appuser 1161 Mar 17 02:50 ensure
connect            | -rwxr-xr-x 1 appuser appuser 1008 Mar 17 02:50 healthcheck.sh
connect            | -rw-rw-r-- 1 appuser appuser  140 Apr 19 08:37 kafka-connect.properties.template
connect            | -rw-r--r-- 1 appuser appuser 1159 Mar 17 02:50 kafka.properties.template
connect            | -rw-rw-r-- 1 appuser appuser 1839 Apr 19 09:19 launch
connect            | -rw-r--r-- 1 appuser appuser  812 Mar 17 02:50 log4j.properties.template
connect            | -rw-r--r-- 1 appuser appuser 1121 Mar 17 02:36 mesos-setup.sh
connect            | -rwxr-xr-x 1 appuser appuser  935 Mar 17 02:50 run
connect            | -rw-r--r-- 1 appuser appuser  305 Mar 17 02:50 tools-log4j.properties.template
```

For the record, in my `include/etc/confluent/docker`, I just added changed some lines in configure and launch scripts.

So I'm confused, am I missing something ? How am I supposed to do this exactly ? Thanks
